name: ${plugin.name}
description: ${plugin.description}
version: ${plugin.version}
api-version: ${versions.api}
main: ${plugin.pkg}.${plugin.class}

depend: [DiscordSRV]

permissions:
  ${plugin.id}.toggle:
    description: Grants access to /discordtoggle
    default: true

commands:
  discordtoggle:
    description: Toggle receiving of Discord messages entirely
    aliases: ["dtoggle"]
    permission: ${plugin.id}.toggle
