name: ${plugin.name}
description: ${plugin.description}
version: ${plugin.version}
api-version: ${versions.api}
main: ${plugin.pkg}.${plugin.class}

authors: [jenbroek]
website: https://github.com/jenbroek/discordsrv-ignore-addon

depend: [DiscordSRV]

permissions:
  ${plugin.id}.toggle:
    description: Grants access to /discordtoggle
    default: true
  ${plugin.id}.ignore:
    description: Grants access to /discordignore and /discordignorelist
    default: true

commands:
  discordtoggle:
    description: Toggle receiving of Discord messages entirely
    aliases: ["dtoggle"]
    permission: ${plugin.id}.toggle
  discordignore:
    description: Toggle receiving of Discord messages from specific users
    usage: "/<command> (PLAYER | DISCORD_UID)..."
    aliases: ["dignore", "discordunignore", "dunignore"]
    permission: ${plugin.id}.ignore
  discordignorelist:
    description: List users whose Discord messages you've ignored
    aliases: ["dignorelist", "discordignored", "dignored"]
    permission: ${plugin.id}.ignore
