name: DiscordSRVIgnoreAddon
description: Allows players to ignore Discord users in Minecraft chat
version: 0.1.0
api-version: 1.20
main: com.github.jenbroek.discordsrv_ignore_addon.DiscordsrvIgnoreAddon
depend: [DiscordSRV]

commands:
  discordignore:
    description: Ignore a Discord user
    usage: "/discordignore <player|discord_id>"
    aliases: []
    permission: discordsrvignoreaddon.ignore
  discordunignore:
    description: Stop ignoring a Discord user
    usage: "/discordunignore <player|discord_id>"
    aliases: []
    permission: discordsrvignoreaddon.ignore
  discordignorelist:
    description: List ignored Discord users
    aliases: []
    permission: discordsrvignoreaddon.ignore

permissions:
  discordsrvignoreaddon.ignore:
    description: Permission to use ignore/unignore commands
    default: true
  discordsrvignoreaddon.toggle:
    description: Permission to use toggle command
    default: true